cmake_minimum_required(VERSION 4.1)
project(SDtA_labs)

set(CMAKE_CXX_STANDARD 20)

add_executable(SDtA_labs task04.cpp
        task-05/task-01.cpp
        task-05/task-02.cpp
        task-05/task-03.cpp
        task-06/task-01.cpp
        task-06/task-02.cpp
        task-06/task-03.cpp
        task-06/task-04.cpp
        task-07/task-01.cpp
        task-07/task-02.cpp
        task-08/task-01.cpp
        task-08/task-02.cpp
)
